### ISSUE TITLE
Deprecation warning for logProductAction

### ISSUE THREAD

**Issue by nstahl** [mParticle/mparticle-web-sdk#13]
I'm receiving a deprecation warning when calling `mParticle.eCommerce.logProductAction` 

![Screen Shot 2019-11-19 at 9 32 49 AM](https://user-images.githubusercontent.com/1687944/69155440-b9bdce00-0aaf-11ea-8780-6ee2ecbb3ac9.png)

Is there a way to avoid this?

**Comment by alexs-mparticle** [comment]
At present, the only way to avoid this deprecation message is to set your `logLevel` to `none`.  However, we will be removing some of the cart functionality in an upcoming release.

Could you give me a list of any other functions that are generating a similar warning, in case we can prioritize their removal?

**Comment by nstahl** [comment]
Thanks @alexs-mparticle. `mParticle.eCommerce.logPromotion` also leads to deprecation warnings. There might be others, those are the two that I'm aware of.

**Comment by rmi22186** [comment]
This has been resolved in [2.11.1](https://github.com/mParticle/mparticle-web-sdk/releases/tag/v2.11.1)
