### ISSUE TITLE
mParticle.eCommerce.logPromotion emits Product Purchased GA Event

### ISSUE THREAD

**Issue by nstahl** [mParticle/mparticle-web-sdk#14]
Using the GA integration, I've noticed that calling `mParticle.eCommerce.logPromotion(mParticle.PromotionType.PromotionView, promotion)` emits a Product Purchased event. This is unexpected behavior when viewing a promotion.

I've posted the code I've used to produce this behavior [here](https://gist.github.com/nstahl/00593a3000639404034631251cf77236).

**Comment by rmi22186** [comment]
Resolved and released in the [Google Integration itself.](https://github.com/mparticle-integrations/mparticle-javascript-integration-google-analytics/pull/14)
