### ISSUE TITLE
Error: "This operation is insecure" on Mobile Safari (iOS 13.x)

### ISSUE THREAD

**Issue by derryl** [mParticle/mparticle-web-sdk#15]
Hello! We've recently moved to the self-hosted mParticle SDK, and I've noticed a few intermittent errors, which I'll post here as I find them.  Happy to provide more info as needed.

Recently, we've seen this error (`SecurityError · The operation is insecure`) occurring in Mobile Safari on devices running either iOS 13.0, 13.1, or 13.2

It occurs when we call `mParticleSDK.init(<api key>, <config>)` and appears to have something to do with accessing LocalStorage on those browsers.

**@mparticle/web-sdk** version: 2.9.13-rc.1

**Error location in source:** `node_modules/@mparticle/web-sdk/dist/mparticle.esm.js:1716:295`

**Comment by alexs-mparticle** [comment]
Hey derryl, could you possibly post some screenshots of your console as well to help us troubleshoot?

**Comment by alexs-mparticle** [comment]
@derryl any update on this? We've tested ourselves and are not seeing this issue. If we don't hear back, we'll close this within a week.

**Comment by alexs-mparticle** [comment]
Closing this issue. If this is still occurring, please make a comment and we can reopen, or create a new issue.
