### ISSUE TITLE
Declaration file

### ISSUE THREAD

**Issue by hatched-esther** [mParticle/mparticle-web-sdk#153]
Do we have a type declaration file for this? I see a types file but Im not sure. 

```
Could not find a declaration file for module '@mparticle/web-sdk'. '/home/app/node_modules/@mparticle/web-sdk/dist/mparticle.common.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mparticle__web-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module '@mparticle/web-sdk';`
```

**Comment by danielraban** [comment]
I am also facing this issue.

**Comment by rmi22186** [comment]
Hi @hatched-esther - this is currently in the works and we are working on getting it released to improve your experience with our SDK.

I assume that the "types" file you're seeing is `src/types.js` which is simply one of the modules in our SDK. It is actually unrelated to TS.

Once this is released I'll follow up on this thread!

**Comment by rmi22186** [comment]
Great news!

The types for mParticle were merged today onto the [DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mparticle__web-sdk)!  The previous instructions in your IDE to run `npm i --save-dev @types/mparticle__web-sdk` should now work.

We'd love your feedback on this improved developer experience, so if you see any issues on your side with the types, please let us know via a new issue in this repo, or feel free to open a PR against the repository above and our team will review it there.

Enjoy!
