### ISSUE TITLE
mParticle Config: appName value not shown in event data

### ISSUE THREAD

**Issue by trevrdspcdev** [mParticle/mparticle-web-sdk#158]
Is it possible to override the `application_name` reported in the event data when sending single events to mParticle using the `logEvent` function? When I set an `appName` property in the mParticle config, the `application_name` in the event data does not change. It consistently shows the application name shown in the upper left corner of the mParticle dashboard.

```json
{
  "application_info": {
    "application_name": "I want to see the appName I specified in the mParticle config"
  }
}
```

If I set an `appName` value in the mParticle config, I would expect to see it as the value for the `application_name` property within the event data. Is there some other way to achieve this?

For context, setting `appVersion` in the mParticle config _does_ affect the `application_version` property value in the event data. I would expect the `appName` property to affect `application_name` in the same way.

Examining the [mParticle code](https://github.com/mParticle/mparticle-web-sdk/blob/a0383bbd975f2271b2b842181b7dc72c7477b2d4/dist/mparticle.js#L3417), it appears that the `appName` property is never used when preparing payloads for single events sent to mParticle. The flow for a single event seems to follow this path:

- I call mParticle.logEvent, which is on line 6428

- it creates an uploadObject by calling createEventObject on line 7602 and passing along the event info

- it then calls sendEventToServer on line 3417, passing along the uploadObject

- sendEventToServer calls sendSingleEventToServer on line 3461, passing along the uploadObject

- sendSingleEventToServer calls convertEventToDTO, passing along the uploadObject

- convertEventToDTO returns the data object that will be sent to mParticle in the xhr request

In `convertEventToDTO`, the `appVersion` property is used here: `av: event.AppVersion`, but the `appName` property is never used and not included in the event data sent to mParticle. Inspecting the payload of calls to mParticle in the browser network tab shows the same.

**Comment by alexs-mparticle** [comment]
@trevrdspcdev Thanks for opening this. I'll have someone take a look at this issue and get back to you as soon as possible.

**Comment by alexs-mparticle** [comment]
Track internally as 69463

**Comment by rmi22186** [comment]
@trevrdspcdev - I took a look at this. It looks like the `config.appName` setting is supported by our V3 events endpoint, and based on my read of your analysis, your organization is likely still on V2, which doesn't support this.  

As we have no plans to continue to support code updates to V2 anymore, I suggest migrating to V3, which your mParticle Customer Success Manager can help with. You can read all about it, and how to confirm which endpoint you are using [here](https://docs.mparticle.com/developers/sdk/web/getting-started/#upload-interval--batching).  There are a wide variety of benefits, as well as a richer payload, which includes sending the `appName`.

I tested this as follows:
The following screenshot is the config I used, and I am on V3 here.
![image](https://user-images.githubusercontent.com/5377436/127021084-45ccbcc7-3545-4a06-970e-ff3d0e4ba673.png)

This is the event in the Live Stream:
![image](https://user-images.githubusercontent.com/5377436/127021255-5eca2bda-d640-4439-84a3-b1eac3515333.png)

Thank you for pointing this out. We will update our docs to state that this configuration item only works on V3.

**Comment by trevrdspcdev** [comment]
> @trevrdspcdev - I took a look at this. It looks like the `config.appName` setting is supported by our V3 events endpoint, and based on my read of your analysis, your organization is likely still on V2, which doesn't support this.
> 
> As we have no plans to continue to support code updates to V2 anymore, I suggest migrating to V3, which your mParticle Customer Success Manager can help with. You can read all about it, and how to confirm which endpoint you are using [here](https://docs.mparticle.com/developers/sdk/web/getting-started/#upload-interval--batching). There are a wide variety of benefits, as well as a richer payload, which includes sending the `appName`.
> 
> I tested this as follows:
> The following screenshot is the config I used, and I am on V3 here.
> ![image](https://user-images.githubusercontent.com/5377436/127021084-45ccbcc7-3545-4a06-970e-ff3d0e4ba673.png)
> 
> This is the event in the Live Stream:
> ![image](https://user-images.githubusercontent.com/5377436/127021255-5eca2bda-d640-4439-84a3-b1eac3515333.png)
> 
> Thank you for pointing this out. We will update our docs to state that this configuration item only works on V3.

@rmi22186 @alexs-mparticle Thanks very much for your assistance!

**Comment by rmi22186** [comment]
Not a problem!  Happy to help 😀

I'll close this issue for now. Let us know if you have any further questions.
