### ISSUE TITLE
Google Ad Manager 360 CookieSync broken for Safari (both desktop and mobile)

### ISSUE THREAD

**Issue by DeeWBee** [mParticle/mparticle-web-sdk#16]
Howdy! 

We self-host the mParticle SDK. Generally, things have been going smoothly! However, we noticed an issue with our Google Ad Manager CookieSync. A majority of our users visit our site via a mobile browser; specifically, iOS Safari. When we attempt to perform a CookieSync on one of these users, we get the following response (split into two screenshots). 

<img width="1178" alt="Screen Shot 2020-03-06 at 12 47 07 PM" src="https://user-images.githubusercontent.com/13024101/76113097-1d113480-5fa9-11ea-99e8-18ace3afa663.png">

<img width="1169" alt="Screen Shot 2020-03-06 at 12 47 35 PM" src="https://user-images.githubusercontent.com/13024101/76113108-226e7f00-5fa9-11ea-85ac-8f55dc9c5f13.png">

Notice the `google_error = 3` and the empty `id` field at the bottom of the 2nd screenshot. When viewing CookieSync operations from other browsers (both desktop and mobile), CookieSync works as expected (no `google_error` and the `id` field is populated). It appears that _only_ Safari experiences this issue (both desktop and mobile). This impacts our audience counts by a significant margin; we see only ~10% of our users feeding through to Google Ad Manager as a result. 

Are you aware of this? We've been working closely with some Solution Consultants (formerly Serena, now Nolan Mattox); but I wanted to get this directly on your radar. Is there anything that can be done? Can we we manually scrub for the cookie and trigger a CookieSync operation? Do you have any insight into what `google_error = 3` represents? Searching online hasn't provided much information. 

Thanks in advance!! Really hope we can figure out a solution!

**Comment by rmi22186** [comment]
Hi @DeeWBee - apologies for the delay, was OOO for a bit. This isn't something that's been reported before. I am not familiar with those errors and will have to open a ticket to investigate internally.

Out of curiosity, and just to get some more information, do you know if it works in a non-self hosted environment?

**Comment by DeeWBee** [comment]
@rmi22186 I haven't had the chance/ability to test non-self hosted environment. Based on what I've read, this probably would occur for both hosted and non-self hosted. It appears that Safari is preventing the Ad Manager cookie from being saved.

**Comment by rmi22186** [comment]
Doing some clean up. Closing as it seems to be a safari issue. Reopen if you have any other questions.
