### ISSUE TITLE
Testing framework?

### ISSUE THREAD

**Issue by DeeWBee** [mParticle/mparticle-web-sdk#18]
Howdy! 

I'm constructing an npm package that is essentially a wrapper around the `web-sdk` package. I'm now writing tests using `sinon` and `mocha`. I want to just stub out the `mParticle` package to test only my package's functionality, but I'm struggling to do so. Running into a lot of namespace issues. It seems that in test conditions, `import mParticle...` returns an undefined object. I can to be able to get around the problem by doing `import * as mParticle...`, but that then introduces a whole new suite of issues within my webpack compiler (via Travis). Have you guys run into anything like this? See the attached image for an example. 

![Screen Shot 2020-04-07 at 7 01 46 AM](https://user-images.githubusercontent.com/13024101/78666948-bb8d0000-789d-11ea-98b1-a1fa91b1c812.png)

Best, 
Darius Bieganski
Digital Analytics Software Engineer 
SportsEngine

**Comment by rmi22186** [comment]
Hey @DeeWBee - interesting, we haven't come across this before. For testing, so long as you're importing there shouldn't be an effect. I'll ping you in a few to set up a time for a screenshare.

**Comment by rmi22186** [comment]
Closing for now after our screenshare, let me know if you need any more help!
