### ISSUE TITLE
setCurrencyCode is not a function

### ISSUE THREAD

**Issue by bryoncdiscovery** [mParticle/mparticle-web-sdk#22]
We are getting this error 'setCurrencyCode is not a function' from time to time and have tracked it down to this code. It seems that when store is not initialized, self.setCurrencyCode is called in the ready callback. The problem is that self is mParticleInstance and does not have a function called setCurrencyCode, because setCurrencyCode is a method of mParticle.eCommerce. 

https://github.com/mParticle/mparticle-web-sdk/blob/c61398e92e76c3057bb23a10813155591dd5bd1b/src/mp-instance.js#L619-L633

**Comment by samdozor** [comment]
@bryoncdiscovery thanks for bring this to our attention! We will take a look ASAP.

**Comment by alexs-mparticle** [comment]
@bryoncdiscovery Sorry for the delay in responding.

It looks like you're a few iterations behind our current SDK. Can you let me know if you've tried updating to our latest SDK and if this is still an issue?

Would you also be willing to share some usage examples of how you're calling `setCurrencyCode`? I'd like to set up something similar to your usage to test for this so I can make sure I've properly resolved the issue.

Thanks!

**Comment by rmi22186** [comment]
@bryoncdiscovery this is fixed as of v2.12.5 which we just released. I am closing this for now, but please reopen if there are any additional issues.  Thanks for the report!
