### ISSUE TITLE
Incorrect function call in generateUniqueId 

### ISSUE THREAD

**Issue by jared-dickman** [mParticle/mparticle-web-sdk#240]
I believe there is a type on line 344 of helpers.js in generateUniqueId

https://github.com/mParticle/mparticle-web-sdk/blob/acd756b041262e033ec6adead16a7135bacd1b0c/src/helpers.js#L344

the function should be called to return a new string recursively, it should probably not attach the string version of the function implementation

**Comment by einsteinx2** [comment]
Tracking internally via https://go.mparticle.com/work/SQDSDKS-4221
