### ISSUE TITLE
Not getting the same mPid each time logout and passing the same identity in other2

### ISSUE THREAD

**Issue by zeelmodi-simform** [mParticle/mparticle-web-sdk#371]
When initialising mParticle, I'm passing a unique Id as other2 Identity as below:

`let mParticleConfig: MPConfiguration = {
    isDevelopmentMode: getIsDevelopmentMode(),
    logLevel: getLogLevel(),
    appVersion: packageJson.version,
    identifyRequest: !isLoggedIn ? {
      userIdentities: {
        other2: visitorId
      }
    } : undefined,
    identityCallback: (result: any) => {
      console.log({ result, identities: result.getUser().getUserIdentities() });
    }
  };
  mParticle.init(`${process.env.REACT_APP_MPARTICLE_API_KEY}`, mParticleConfig);`

And when my user is logged out, I'm doing the following:

`const identityRequest: IdentityApiData = {
    userIdentities: {
      other2: visitorId
    }
  };`

`mParticle.Identity.logout(identityRequest, (res) => {
    console.log('after logout ',{res, mPId: res.getUser().getMPID(), identities: res.getUser().getUserIdentities()});

    if (res.getUser()) {
      res.getUser().getMPID()
      res.getUser().getUserIdentities()      
    }
  });`

**Comment by twaner** [comment]
Hi @zeelmodi-simform - We're happy to help you with this question. Can you create a [support ticket](https://support.mparticle.com/hc/en-us), and we will triage from there?

**Comment by twaner** [comment]
Hi @zeelmodi-simform - we plan to close this out. Please visit our [support portal](https://support.mparticle.com/hc/en-us) to create a ticket, and we will triage this issue.

**Comment by rmi22186** [comment]
Hi @zeelmodi-simform - as @twaner said, this would best be triaged via a support ticket. Please follow his instructions above as I am closing this ticket out.
