### ISSUE TITLE
[Bug] NPM Build Script - 'ENVIRONMENT' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Ahmedie-m** [mParticle/mparticle-web-sdk#88]
Hey guys,

There seems to be a bug when running npm build. I have confirmed that rollup is infact installed and made sure it matches the same version as the one in package.json.

Below is the error given when attempting to run: `npm run build`

```
> @mparticle/web-sdk@2.12.3 build D:\Work\mparticle-web-sdk
> ENVIRONMENT=prod BUILDALL=true rollup --config rollup.config.js

'ENVIRONMENT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @mparticle/web-sdk@2.12.3 build: `ENVIRONMENT=prod BUILDALL=true rollup --config rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @mparticle/web-sdk@2.12.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Is there a solution to this? Thanks!

**Comment by rmi22186** [comment]
It appears this this may be related to the OS you are using. Are you on windows?  It looks like a package like [cross-env](https://www.npmjs.com/package/cross-env) may help with this. I can add this to our backlog, but you can also feel free to test this out locally and see if you can get a PR going 
also. We love open source contributions!

**Comment by rmi22186** [comment]
PR #118  fixes this
