### ISSUE TITLE
not working in extension manifest v3

### ISSUE THREAD

**Issue by rajsko** [mParticle/mparticle-web-sdk#896]
I did not manage to get mpartickle web sdk to run in chrome extension with manifest v3, which runs entirely in service worker that do no support XHR. The events are nor tracked an when I try to set identity only then I get error of `Error creating XMLHttpRequest object.`. I know you replace xhr with fetch during batching but probably xhr is not replaced everywhere. Am I doing something wrong or is this known issue?

**Comment by alexs-mparticle** [comment]
@rajsko Thanks for raising this issue. I'll discuss this with the team and see if we can reproduce. Out of curiosity, can you provide screen shots of any errors related to mParticle in your browser's Network tab or Console? This would help us with our investigation.

**Comment by rajsko** [comment]
Thanks for swift reply!
no error initially in console nor in network tab, only this  gets logged after I try to call `mParticle.Identity.login`
<img width="279" alt="Screenshot 2024-07-22 at 16 18 18" src="https://github.com/user-attachments/assets/5c255585-ff84-465d-8349-36ee9dc6ffcd">

But I think this might help, this is the mparticle instance after initialization. I think some fields are missing like for example `_APIClient`.

![Screenshot 2024-07-22 at 16 17 21](https://github.com/user-attachments/assets/c8a6d7a3-f9b6-4ae5-83ca-eeff7c417647)

**Comment by alexs-mparticle** [comment]
Thank you for the screen shots. We don't have an ETA on the fix but we have begun investigating and will update this issue when we have a solution.

**Comment by rajsko** [comment]
Thanks, though you be able to clarify the ETA horizon in terms of days, weeks, or months?

**Comment by alexs-mparticle** [comment]
We'll be investigating this issue within the next week and we'll be able to give you a more accurate estimate timeline then. It will likely be a few weeks before this is released and we'll tag this issue so you can be updated once it is live.

If you need this prioritized more urgently or would like a tracking ticket, please reach out to our Support Team at [support@mparticle.com](mailto:support@mparticle.com).

**Comment by alexs-mparticle** [comment]
Closing as this was fixed by #932, #919, #917, #908, #907, #905, #904 and #898
