### ISSUE TITLE
Unable to let server set timestamps

### ISSUE THREAD

**Issue by gmhewett** [mParticle/mparticle-web-sdk#916]
## Motivation 

When working with the web SDK, it would be nice to allow the server to set the timestamps for the events. Based on the [mParticle docs](https://support.mparticle.com/hc/en-us/articles/7004272100365-What-is-the-Difference-Between-Batch-and-Event-Timestamp):

> Thetimestamp_unixtime_ms represents the timestamp of event. The current server time will be used if not specified.

However, this is not currently possible with the web sdk.

## Current State

From my understanding, as of now the event timestamps are set as follows in `src/serverModel.ts`:

First, the `dateLastEventSent` is set via `new Date()` ([link](https://github.com/mParticle/mparticle-web-sdk/blob/master/src/serverModel.ts#L346)):

```ts
if (event.messageType !== Types.MessageType.SessionEnd) {
    mpInstance._Store.dateLastEventSent = new Date();
}
```

Then, the event timestamp is set using this value ([link](https://github.com/mParticle/mparticle-web-sdk/blob/master/src/serverModel.ts#L403)):

```ts
uploadObject.Timestamp = mpInstance._Store.dateLastEventSent.getTime();
```

Because of this, manually setting `timestamp_unixtime_ms` in an event has no effect.

## Suggested changes

The issue I have is that it's not possible to get a "ground truth" timestamp for when the event hit the server. If the user's system clock is off, then the timestamps will be off. To support this, it would be nice to have either

1. A config option for using client-based timestamps, or
1. The ability to manually set the `timestamp_unixtime_ms` value to `null` or `undefined` to ensure it's not overwritten by the SDK.

Thanks in advance for taking a look!

**Comment by alexs-mparticle** [comment]
Closing this ticket as workaround has been identified.
